name: Validate Gradle Wrapper

on:
  push:
    branches:
      - master
  pull_request:
    # always run on pull requests

jobs:
  gradlevalidation:
    name: "Validate Gradle Wrapper"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
